### ISSUE TITLE
Does that work for an entire subdomain?

### ISSUE THREAD

**Issue by jmfayard** [TheDancingCode/password-protected-pages-on-netlify#1]
Hello awesome article and nice to have the code along.

My usecase is a bit different. 
https://jmfayard.dev/ is public
But I want to deploy a private subdomain, let say at https://private.jmfayard.dev/

I am totally new to typescript and netlify function.
Can your solution be adapted to that use case?

**Comment by TheDancingCode** [comment]
Yes, you'd simply redirect everything on the subdomain by adapting the glob:
```toml
[[redirects]]
  from = "/*"
```
